<div class="row">
    <div class=" col-lg-2"></div>
    <div class=" col-lg-8">
	<div class="panel">
	    <div class="panel-heading">
		<div class="panel-title">
		    <h3><i class="glyphicon glyphicon-log-in"></i> <?php echo $this->translate('Login'); ?></h3>
		</div>
	    </div>
	    <div class="panel-body">
		<?php echo $this->losForm($this->entityForm); ?>
	    </div>
	</div>
    </div>
    <div class=" col-lg-2"></div>
</div>